version: "3.7"

# Services
services:

  # Seleniarm, bukan selenium.
  # Ini sebaiknya ada di file docker-compose lain (with -f)
  chrome:
    image: seleniarm/standalone-chromium:104.0
    hostname: chrome
    container_name: ${APP_NAME}-chrome
    privileged: true
    shm_size: 2g
    ports:
      - '4444:4444'
      - '7900:7900'
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - ${APP_NAME}-network