version: "3.7"

# SERVICES
services:

  # gulp untuk compile sass
  gulp :
    image: node:16.17.0-slim
    hostname: gulp
    container_name: ${APP_NAME}-gulp
    build:
      context: "."
      dockerfile: "./.docker/node/Dockerfile"
    working_dir: /var/www/html
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/var/www/html
    networks:
      - ${APP_NAME}-network
    depends_on:
      - php