version: "3.7"

# SERVICES
services:

  # MAIN DATABASE
  db:
    image: mysql:8.0.28-oracle
    hostname: mysql
    container_name: ${APP_NAME}-db
    tty: false
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ${APP_NAME}-volumes:/var/lib/mysql/
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - ${APP_NAME}-network
    ports:
      - ${DB_PORT}:3306

  # PHP, Yii2 framework disini
  php:
    image: "${REGISTRY_HOST}/${APP_NAME}-php"
    hostname: php
    build:
      context: "."
      target: ${TARGET} # set ke deploy saat akan production
      dockerfile: "./.docker/php/debian-apache/Dockerfile"
    container_name: ${APP_NAME}-php
    tty: true
    working_dir: /var/www/html
    ports:
      - "${WEB_SERVER_PORT}:80"
    env_file:
      - .env
    volumes:
      - ./:/var/www/html # Only for local dev, gunakan copy untuk production (Lihat build Dockerfile)
    networks:
      - ${APP_NAME}-network
    depends_on:
      - db

# Docker Networks
networks:
  tms-starter-network:
    driver: bridge

# Docker Volumes
volumes:
  tms-starter-volumes:
    driver: local