version: "3.7"

# SERVICES
services:

  # PHP, Yii2 framework disini
  php:
    platform: linux/amd64
    image: "${REGISTRY_HOST}/${APP_NAME}-php"
    hostname: php
    build:
      context: "."
      target: deploy # set ke deploy saat akan production
      dockerfile: "./.docker/php/debian-apache/Dockerfile"
    container_name: ${APP_NAME}-php
    tty: true
    working_dir: /var/www/html
    ports:
      - "${WEB_SERVER_PORT}:80"
    env_file:
      - .env