<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "barang".
 *
 * @property integer $id
 * @property string $nama
 * @property string $part_number
 * @property integer $satuan_id
 *
 * @property \app\models\Satuan $satuan
 * @property string $aliasModel
 */
abstract class Barang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'barang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'satuan_id'], 'required'],
            [['satuan_id'], 'integer'],
            [['nama'], 'string', 'max' => 255],
            [['part_number'], 'string', 'max' => 32],
            [['part_number'], 'unique'],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'part_number' => 'Part Number',
            'satuan_id' => 'Satuan ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\BarangQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\BarangQuery(get_called_class());
    }


}
