<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "barang_satuan".
 *
 * @property integer $id
 * @property integer $vendor_id
 * @property integer $barang_id
 * @property integer $satuan_id
 * @property string $harga_beli
 * @property string $harga_jual
 *
 * @property \app\models\Barang $barang
 * @property \app\models\Satuan $satuan
 * @property \app\models\Card $vendor
 * @property string $aliasModel
 */
abstract class BarangSatuan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'barang_satuan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vendor_id', 'satuan_id', 'harga_jual'], 'required'],
            [['vendor_id', 'barang_id', 'satuan_id'], 'integer'],
            [['harga_beli', 'harga_jual'], 'number'],
            [['barang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Barang::class, 'targetAttribute' => ['barang_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'vendor_id' => 'Vendor ID',
            'barang_id' => 'Barang ID',
            'satuan_id' => 'Satuan ID',
            'harga_beli' => 'Harga Beli',
            'harga_jual' => 'Harga Jual',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarang()
    {
        return $this->hasOne(\app\models\Barang::class, ['id' => 'barang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\BarangSatuanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\BarangSatuanQuery(get_called_class());
    }


}
