<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "cache".
 *
 * @property string $id
 * @property integer $expire
 * @property resource $data
 * @property string $aliasModel
 */
abstract class Cache extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cache';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['expire'], 'integer'],
            [['data'], 'string'],
            [['id'], 'string', 'max' => 128],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'expire' => 'Expire',
            'data' => 'Data',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\CacheQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\CacheQuery(get_called_class());
    }


}
