<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "card_belongs_type".
 *
 * @property integer $id
 * @property integer $card_id
 * @property integer $card_type_id
 *
 * @property \app\models\Card $card
 * @property \app\models\CardType $cardType
 * @property string $aliasModel
 */
abstract class CardBelongsType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'card_belongs_type';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['card_id', 'card_type_id'], 'integer'],
            [['card_type_id'], 'required'],
            [['card_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['card_id' => 'id']],
            [['card_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CardType::class, 'targetAttribute' => ['card_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'card_id' => 'Card ID',
            'card_type_id' => 'Card Type ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCard()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'card_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCardType()
    {
        return $this->hasOne(\app\models\CardType::class, ['id' => 'card_type_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\CardBelongsTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\CardBelongsTypeQuery(get_called_class());
    }


}
