<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "card".
 *
 * @property integer $id
 * @property string $nama
 * @property string $kode
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\BarangSatuan[] $barangSatuans
 * @property \app\models\CardBelongsType[] $cardBelongsTypes
 * @property \app\models\FakturDetail[] $fakturDetails
 * @property \app\models\Faktur[] $fakturs
 * @property \app\models\Faktur[] $fakturs0
 * @property string $aliasModel
 */
abstract class Card extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'card';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'kode'], 'required'],
            [['nama'], 'string', 'max' => 255],
            [['kode'], 'string', 'max' => 50]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'kode' => 'Kode',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarangSatuans()
    {
        return $this->hasMany(\app\models\BarangSatuan::class, ['vendor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCardBelongsTypes()
    {
        return $this->hasMany(\app\models\CardBelongsType::class, ['card_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFakturDetails()
    {
        return $this->hasMany(\app\models\FakturDetail::class, ['vendor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFakturs()
    {
        return $this->hasMany(\app\models\Faktur::class, ['card_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFakturs0()
    {
        return $this->hasMany(\app\models\Faktur::class, ['toko_saya_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\CardQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\CardQuery(get_called_class());
    }


}
