<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "faktur".
 *
 * @property integer $id
 * @property string $tanggal_faktur
 * @property string $nomor_faktur
 * @property string $nomor_purchase_order
 * @property integer $jenis_transaksi_id
 *
 * @property \app\models\FakturDetail[] $fakturDetails
 * @property \app\models\JenisTransaksi $jenisTransaksi
 * @property string $aliasModel
 */
abstract class Faktur extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'faktur';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tanggal_faktur'], 'safe'],
            [['jenis_transaksi_id'], 'required'],
            [['jenis_transaksi_id'], 'integer'],
            [['nomor_faktur', 'nomor_purchase_order'], 'string', 'max' => 255],
            [['jenis_transaksi_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JenisTransaksi::class, 'targetAttribute' => ['jenis_transaksi_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tanggal_faktur' => 'Tanggal Faktur',
            'nomor_faktur' => 'Nomor Faktur',
            'nomor_purchase_order' => 'Nomor Purchase Order',
            'jenis_transaksi_id' => 'Jenis Transaksi ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFakturDetails()
    {
        return $this->hasMany(\app\models\FakturDetail::class, ['faktur_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisTransaksi()
    {
        return $this->hasOne(\app\models\JenisTransaksi::class, ['id' => 'jenis_transaksi_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\FakturQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\FakturQuery(get_called_class());
    }


}
