<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "faktur_detail".
 *
 * @property integer $id
 * @property integer $faktur_id
 * @property integer $barang_id
 * @property string $quantity
 * @property integer $satuan_id
 * @property integer $vendor_id
 * @property string $harga_barang
 *
 * @property \app\models\Barang $barang
 * @property \app\models\Faktur $faktur
 * @property \app\models\Satuan $satuan
 * @property \app\models\Card $vendor
 * @property string $aliasModel
 */
abstract class FakturDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'faktur_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['faktur_id', 'barang_id', 'satuan_id', 'vendor_id'], 'integer'],
            [['barang_id', 'quantity', 'satuan_id', 'vendor_id', 'harga_barang'], 'required'],
            [['quantity', 'harga_barang'], 'number'],
            [['barang_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Barang::class, 'targetAttribute' => ['barang_id' => 'id']],
            [['faktur_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Faktur::class, 'targetAttribute' => ['faktur_id' => 'id']],
            [['satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Satuan::class, 'targetAttribute' => ['satuan_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Card::class, 'targetAttribute' => ['vendor_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'faktur_id' => 'Faktur ID',
            'barang_id' => 'Barang ID',
            'quantity' => 'Quantity',
            'satuan_id' => 'Satuan ID',
            'vendor_id' => 'Vendor ID',
            'harga_barang' => 'Harga Barang',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarang()
    {
        return $this->hasOne(\app\models\Barang::class, ['id' => 'barang_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFaktur()
    {
        return $this->hasOne(\app\models\Faktur::class, ['id' => 'faktur_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\Satuan::class, ['id' => 'satuan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(\app\models\Card::class, ['id' => 'vendor_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\FakturDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\FakturDetailQuery(get_called_class());
    }


}
