<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "item_detail_detail".
 *
 * @property integer $id
 * @property integer $item_detail_id
 * @property string $name
 * @property string $dropdown_item
 *
 * @property \app\models\ItemDetail $itemDetail
 * @property string $aliasModel
 */
abstract class ItemDetailDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_detail_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['item_detail_id'], 'integer'],
            [['name'], 'required'],
            [['name', 'dropdown_item'], 'string', 'max' => 255],
            [['item_detail_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ItemDetail::class, 'targetAttribute' => ['item_detail_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'item_detail_id' => 'Item Detail ID',
            'name' => 'Name',
            'dropdown_item' => 'Dropdown Item',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemDetail()
    {
        return $this->hasOne(\app\models\ItemDetail::class, ['id' => 'item_detail_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\ItemDetailDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\ItemDetailDetailQuery(get_called_class());
    }


}
