<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "item".
 *
 * @property integer $id
 * @property string $name
 * @property string $tanggal
 * @property string $tanggal_waktu
 *
 * @property \app\models\ItemDetail[] $itemDetails
 * @property string $aliasModel
 */
abstract class Item extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['tanggal', 'tanggal_waktu'], 'safe'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'tanggal' => 'Tanggal',
            'tanggal_waktu' => 'Tanggal Waktu',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemDetails()
    {
        return $this->hasMany(\app\models\ItemDetail::class, ['item_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\ItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\ItemQuery(get_called_class());
    }


}
