<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "rekening".
 *
 * @property integer $id
 * @property string $atas_nama
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\Faktur[] $fakturs
 * @property \app\models\RekeningDetail[] $rekeningDetails
 * @property string $aliasModel
 */
abstract class Rekening extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rekening';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['atas_nama'], 'required'],
            [['atas_nama'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'atas_nama' => 'Atas Nama',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFakturs()
    {
        return $this->hasMany(\app\models\Faktur::class, ['rekening_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRekeningDetails()
    {
        return $this->hasMany(\app\models\RekeningDetail::class, ['rekening_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\RekeningQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\RekeningQuery(get_called_class());
    }


}
