<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "satuan".
 *
 * @property integer $id
 * @property string $nama
 *
 * @property \app\models\Barang[] $barangs
 * @property string $aliasModel
 */
abstract class Satuan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'satuan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['nama'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarangs()
    {
        return $this->hasMany(\app\models\Barang::class, ['satuan_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\active_queries\SatuanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\active_queries\SatuanQuery(get_called_class());
    }


}
