name: Init composer
on:
  push:
    branches: ["main"]

jobs:
  run-composer:
    name: composer initialization
    runs-on: ubuntu-latest
    steps:
              
      - name: Check out the repo
        uses: actions/checkout@v3
          
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Running composer install
        run: composer install --no-dev
