name: CI
on:
  push:
    branches: ["main"]

jobs:
  run-composer-and-docker:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
              
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
                  
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Running composer install
        run: composer install --no-dev
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: deploy
          file: "./.docker/php/debian-apache/Dockerfile"
          push: true
          tags: dziljalal/stm-php:latest
          cache-from: type=registry,ref=dziljalal/stm-php:latest
          cache-to: type=inline
          
      - name: Remote SSH DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd stm
            docker-compose down && docker-compose pull && docker-compose up -d
            docker exec -it stm-php php yii migrate --interactive=0
